config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: "posts"
  post '/', to: 'posts#create'
  get '/signup', to: 'users#new'
  resources 'posts', only: [:show, :new, :destroy] do # remove user index for actual production
    resources 'comments', only: [:create, :destroy]
  end
  resources 'users', except: [:new, :index, :destroy] do # remove user index for actual production
    resources 'comments', only: [:index]
  end
  get 'users/:id/edit_password', to: "users#edit_password", as: "edit_password"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :users, through: :comments
  validates :title, :content, presence: true
  validates :url, length: { minimum: 0 }, url: true
  attr_accessor :commentor_count

  def has_link?
    !!self.url && self.url =~ /\w/
  end
  def comment_count
    self.comments.length
  end

  def unique_user_count #im dumb
    self.users.uniq.length
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :posts

  has_many :comments
  has_many :commented_posts, :through => :comments, :source => :post
  has_secure_password
  validates :name, :email, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates_confirmation_of :password
end

app/models/url_validator.rb
class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /(https?:\/\/).+\.[a-z]{2,}/i || value.blank?
      record.errors[attribute] << (options[:message] || "is not an acceptable url type")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :commented_posts, :through => :comments, :source => :post
  has_secure_password
  validates :username, :email, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :email, presence: true, email: true
  validates_confirmation_of :password

  def num_posts 
    self.posts.count > 0 ? "written #{self.posts.count}" : "not written any"
  end 

  def num_commented_posts
    self.commented_posts.count > 0 ? "commented on #{self.commented_posts.count}" : "not commented on any" 
  end 
  
  # written or commented on are the only option
  def num_things(write_or_comment)
    return write_or_comment == "written" ? self.posts.count : self.commented_posts.uniq.count
  end 

  def num_things_words(w_o_c)
    things_count = num_things(w_o_c)
    return things_count > 0 ? "#{w_o_c} #{things_count}" : "not #{w_o_c} any"
  end 



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionView::Helpers::TextHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 

  def logged_in?
    # this is extra explicit
    !!session[:user_id] ? true : false 
  end 

  def matched_user?(user)
    current_user.id == user.id if current_user
  end 

  def nice_format(user, text)
    str = matched_user?(user) ? "You have" : "#{user.username} has"
    if user.num_things(text) == 1
      return "#{str} #{user.num_things_words(text)} post"
    else 
      return "#{str} #{user.num_things_words(text)} posts"
    end 
  end 

  # now you can call this method in your views by adding this line
  helper_method :current_user, :matched_user?, :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @nice_format_posts_commented = nice_format(@user, "commented on")
  end
  def create
    # the request.referer returns the page the form came from:
    #     https:/site.com/posts/2
    # so we use regex to pull the post number to use as our id
   content = params[:comment][:content]

   # checks to see if there are any words in the comment
   if content =~ /\w/
     user_id = session[:user_id]
     Comment.create(user_id: user_id, post_id: params[:post_id], content: content)
   else
     flash[:comment_warning] = "Don't leave a blank comment"
   end
   redirect_to post_path(params[:post_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy
    redirect_to post_path(post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    if logged_in?
      @post = Post.new
    else
      flash[:log_in_warning] = "You have to be logged in to make a new post"
      redirect_to login_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render "new"
    end
  end
  def destroy
    @post.comments.destroy_all
    @post.delete
    redirect_to posts_path
  end
  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to(posts_path) if logged_in?
  end

  def create
    @user = User.where('LOWER(username) = LOWER(?)', params[:username])[0]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:log_in_warning] = "Your password or username was incorrect."
      render "new"
    end
  end

  def destroy
    session.delete :user_id
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :edit_password]

  def show
    @nice_format_posts_written = nice_format(@user, "written")
  end

  def new
    if logged_in?
      redirect_to posts_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def edit
    edit_gaurd
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def edit_password
    edit_gaurd
  end

  private
    def user_params
      params.require(:user).permit(:username, :email,:bio,  :password, :password_confirmation)
    end
    def set_user
      @user = User.find(params[:id])
    end

    def edit_gaurd
      redirect_to user_path(@user) unless matched_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/index.html.erb
<div class="form-holder wide">
<%= render 'users/user' %>
<p class="psu-heading-2 left">
  <%= link_to "see posts by #{@user.username}", user_path(@user) %>
  <%= @nice_format_posts_commented %>
</p>

  <div class="user-posts">
    <%@user.commented_posts.uniq.each do |post| %>
      <hr />
        <%= link_to post.title, post_path(post), class: "user-post-title" %>
      <div class="comments-scroll">
        <% post.comments.each do |comment| %>
          <% if comment.user == @user %>
          <p class="user-comment-content">  "<%= comment.content%>"</p>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodePost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i" rel="stylesheet">
  </head>
  <body>
    <header>
      <p><%= link_to "[code_post]", posts_path, class: "p-heading" %></p>
      <nav>

        <%= link_to "posts", posts_path %>
        <% if logged_in? %>
          <%= link_to current_user.username, user_path(session[:user_id]) %> 
          <%= link_to "log out", logout_path, method: "post" %>
        <% else %>
          <%= link_to "sign up", signup_path %> 
          <%= link_to "log in", login_path %>
        <% end %>
      </nav>  
 
    </header>
    <main role="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="login-create-holder">
  
<% if logged_in? %>
    <p class="psu-heading">share some code</p>
    <%= link_to "create a post", new_post_path %>
  <% else %>
    <p class="psu-heading">log in</p>
    <%= render 'sessions/login_form' %>
  </div>
<% end %>
</div>

<div class="main-posts-holder">
     <% @posts.each do |post| %>
       <div class="post-box">
         <p class="post-title"><%= link_to post.title, post_path(post) %></p>
         <div class="post-links-holder">
           <p class="post-links">
             <%= link_to "view post", post_path(post) %> l 
             <%= pluralize(post.comment_count, "comment")%> l 
             <%= pluralize(post.unique_user_count, "user")%> l 
           </p>
           <p class="post-author"><%= link_to post.user.username, user_path(post.user)%></p>
         </div>
         <hr />
       </div>
     <% end %>
</div>

app/views/posts/new.html.erb
<div class="form-holder">
  <p class="psu-heading">new post</p>
  <% @post.errors.full_messages.each do |error| %>
    <div class="notice"><span>*</span><%= error %></div>
  <% end %>
  <%= form_for @post do |f| %>
    <%= f.text_field :title, placeholder: "title" %><br><br>
    <%= f.text_area :content, placeholder: "main content" %><br><br>

    <%= f.text_field :url, placeholder: "Optional url to article/project"%><br><br>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-holder">
  <div class="post-box">
    <p class="post-title"><%= @post.title %></p>
    <p class="post-content"><%= @post.content %></p>
    <% if @post.has_link? %>
      <p class="post-url">
        <%= link_to "visit link", @post.url, target: :_blank %> 
      </p>
    <% end %>
    <p class="post-author-main">
      By <%= link_to @post.user.username, user_path(@post.user) %>
    </p>
    <hr />
  </div>
  <% if logged_in? %>

  <p class="psu-heading-2">Leave a Comment</p>
  <% if flash[:comment_warning] %>
    <div class="notice"><span>*</span><%= flash[:comment_warning] %></div>
  <% end %>

  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :content %><br />
    <button type="submit">post comment</button>
  <% end %>

<% else %>
  <p class="log-in-warning">please <%= link_to "log in", login_path %> to leave a comment</p>
<% end %>

<p class="psu-heading-2 left">comments</p>
<% @post.comments.each do |comment| %>
  <hr />
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-author">-<%= link_to comment.user.username, user_path(comment.user) %></p> 
  <% if matched_user?(comment.user) %>
    <%= button_to "Delete Comment", post_comment_path(@post, comment), method: "delete" %>
  <% end %>
  <hr />
<% end %>

<% if matched_user?(@post.user) %>
  <br /><br /><br />
  <%= button_to 'Delete Post', post_path(@post), method: 'delete' %>
<% end %>
</div>

app/views/profiles/_form.html.erb
<h1>NEW FORM HERE </h1>
<% if @profile.errors.any? %>
  <ul>
    <% @profile.errors.full_messages.each do |error| %>
       <li><%= error %></li>
    <% end %>
  </ul>


<% end %>
<%= form_for @profile do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Your username here"%><br />

  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "user@example.com" %><br />

  <%= f.label :password %>
  <%= f.password_field :password %><br />

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <div class="notice"><span>*</span><%= error %></div>
  <% end %>
<% end %>
<%= f.text_field :username, placeholder: "Your username here"%><br />

<%= f.email_field :email, placeholder: "user@example.com" %><br />

app/views/users/_user.html.erb
<div class="user-profile">
  <div "username-bio-holder">
    <p class="psu-heading left">  <%= @user.username %></p> 
    <p class="comment-content left"><%= @user.bio %></p>
  </div>
  <% if matched_user?(@user) %>
    <div class="edit-button-holder">
      <%=link_to "Edit User info", edit_user_path(@user)%><br>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="form-holder">
  
  <p class="psu-heading">edit page</p>
  <%= form_for @user do |f| %>
  <%=render partial: 'form', locals: {f: f}%>
  <%= f.text_area :bio %>
  <br>
 
  <button type="submit">update info</button>


  <% end %>
  <br><br>
  <%= link_to "edit password", edit_password_path %>
  <%= link_to "back to user ", user_path(@user) %>
</div>

app/views/users/edit_password.html.erb
<div class="form-holder">
  
  <p class="psu-heading">edit password</p>
  <%= form_for @user do |f| %>
    <%= f.password_field :password, placeholder: "password"%><br />
    <%= f.password_field :password_confirmation, placeholder: "password confirmation" %><br />
    <button type="submit">update password</button>
  <% end %>
  <%= link_to "back to user info", edit_user_path %>
</div>

app/views/users/new.html.erb
<div class="form-holder">
<p class="psu-heading">sign up</p>
<%= form_for @user do |f| %>
<%=render partial: 'form', locals: {f: f}%>

<%= f.password_field :password, placeholder: "password" %><br />

<%= f.password_field :password_confirmation, placeholder: "password confirmation"%><br />


  <button type="submit">sign up!</button>
<% end %>
</div>

app/views/users/show.html.erb
<div class="form-holder wide">
<%=render 'user'%>
<p class="psu-heading-2 left">
   <%= link_to "see posts #{@user.username} commented on", user_comments_path(@user) %>
   <%= @nice_format_posts_written %>
</p>

<div class="user-posts">
  <% @user.posts.each do |post| %>
    <hr />
    <%= link_to post.title, post_path(post), class: "user-post-title" %><br />
<% end %>
</div>

</div>